blueprint:
  name: HVAC Pause
  description: >-
    Version: 1.8.0
    Pauses HVAC when windows/doors open; resumes last state once closed. Includes temperature override protection. [Full documentation](https://github.com/dpredster/HomeAssistantBlueprints/blob/main/hvac_pause.md)


    ### Credits

    * [@raffy-ops](https://github.com/raffy-ops) — [Initial blueprint](https://gist.github.com/raffy-ops/2bdf967036d8d274fb1f62572ed5e545)
  domain: automation
  source_url: https://github.com/dpredster/HomeAssistantBlueprints/blob/main/hvac_pause.yaml
  input:
    climate_device:
      description: Climate entity used for climate control.
      name: Climate Device
      selector:
        entity:
          domain:
          - climate
          multiple: false
    doors_windows:
      description: Group of entities that will activate automation. (Assumes 'on'
        means 'open')
      name: Door and window sensors.
      selector:
        entity:
          domain:
          - group
          - binary_sensor
          multiple: false
    pause_delay:
      description: Time to wait before pausing the HVAC system.
      name: Pause Delay
      default:
        hours: 0
        minutes: 5
        seconds: 0
      selector:
        duration: {}
    resume_delay:
      description: Time to wait before resuming the HVAC system once doors and windows are closed.
      name: Resume Delay
      default:
        hours: 0
        minutes: 0
        seconds: 30
      selector:
        duration: {}
    timeout:
      description: If set, HVAC will ramain off if door/window is not closed prior to timeout value elapsing.
        Set to 0 to disable timeout.
      name: Timeout (optional)
      default:
        hours: 0
        minutes: 0
        seconds: 0
      selector:
        duration: {}
    enable_temp_override:
      description: Enable temperature override feature to resume HVAC if temperature goes outside defined range.
      name: Enable Temperature Override
      default: false
      selector:
        boolean: {}
    temp_sensor:
      description: Temperature sensor to monitor for override conditions.
      name: Temperature Sensor (Optional)
      default: sensor.none
      selector:
        entity:
          domain:
          - sensor
          device_class:
          - temperature
          multiple: false
    temp_min:
      description: Minimum temperature threshold. HVAC resumes if temperature falls below this value. Set to -999 to disable minimum threshold.
      name: Minimum Temperature
      default: -999
      selector:
        number:
          min: -999
          max: 50
          step: 0.5
          unit_of_measurement: "°C"
          mode: box
    temp_max:
      description: Maximum temperature threshold. HVAC resumes if temperature exceeds this value. Set to 999 to disable maximum threshold.
      name: Maximum Temperature
      default: 999
      selector:
        number:
          min: -20
          max: 999
          step: 0.5
          unit_of_measurement: "°C"
          mode: box
    temp_override_duration:
      description: How long temperature must be outside range before resuming HVAC.
      name: Temperature Override Duration
      default:
        hours: 0
        minutes: 5
        seconds: 0
      selector:
        duration: {}
    action_first:
      description: When set to On any defined 'Pause Actions' will occur after the pause delay and prior to
        any other actions.
      name: Action First
      default: false
      selector:
        boolean: {}
    pause_action:
      description: Optional additional action to perform when climate entity is paused.
      name: Pause Action (Optional)
      default: []
      selector:
        action: {}
    resume_action:
      description: Optional additional action to perform when climate entity resumes.
      name: Resume Action (Optional)
      default: []
      selector:
        action: {}
    temp_override_action:
      description: Optional additional action to perform when temperature override activates.
      name: Temperature Override Action (Optional)
      default: []
      selector:
        action: {}
    timeout_action:
      description: Optional additional action to perform if the timeout value elapses.
      name: Timeout Action (Optional)
      default: []
      selector:
        action: {}
variables:
  action_first: !input action_first
  pause_action: !input pause_action
  resume_action: !input resume_action
  temp_override_action: !input temp_override_action
  timeout_action: !input timeout_action
  climate_device: !input climate_device
  doors_windows: !input doors_windows
  timeout: !input timeout
  timeout_empty: {'hours':00, 'minutes':00, 'seconds':00}
  name_id: '{{ state_attr( climate_device ,''friendly_name'')|slugify ~ ''_snapshot'' }}'
  button_entity: '{{ ''button.'' ~ name_id ~ ''_clear_hold'' }}'
  enable_temp_override: !input enable_temp_override
  temp_sensor: !input temp_sensor
  temp_min: !input temp_min
  temp_max: !input temp_max

mode: single
trigger:
- platform: state
  entity_id: !input doors_windows
  from: 'off'
  to: 'on'
  for: !input pause_delay
  id: group_open
- platform: numeric_state
  entity_id: !input temp_sensor
  below: !input temp_min
  for: !input temp_override_duration
  id: temp_too_low
  enabled: '{{ enable_temp_override and temp_sensor not in ["sensor.none", "unavailable", "unknown"] and temp_min > -999 }}'
- platform: numeric_state
  entity_id: !input temp_sensor
  above: !input temp_max
  for: !input temp_override_duration
  id: temp_too_high
  enabled: '{{ enable_temp_override and temp_sensor not in ["sensor.none", "unavailable", "unknown"] and temp_max < 999 }}'
condition: []
action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - temp_too_low
      - temp_too_high
    - condition: template
      value_template: '{{ enable_temp_override == true }}'
    - condition: state
      entity_id: !input climate_device
      state: 'off'
    sequence:
    - service: scene.turn_on
      target:
        entity_id: '{{ ''scene.'' ~ name_id ~ ''_snapshot'' }}'
    - choose:
      - conditions:
        - condition: template
          value_template: '{{ ''ecobee'' in device_attr( climate_device ,''manufacturer'') |lower }}'
        - condition: template
          value_template: '{{ states(button_entity) != "unknown" }}'
        sequence:
          - delay:
              seconds: 1
          - service: button.press
            metadata: {}
            data: {}
            target:
              entity_id: '{{ button_entity }}'
    - choose:
      - conditions: '{{ resume_action is defined }}'
        sequence: !input resume_action
    - choose:
      - conditions: '{{ temp_override_action is defined }}'
        sequence: !input temp_override_action
    - stop: 'Temperature override activated - HVAC resumed'
- condition: trigger
  id:
  - group_open
- condition: not
  conditions:
  - condition: state
    entity_id: !input climate_device
    state: 'off'
- choose:
  - conditions: '{{ pause_action is defined and action_first == true }}'
    sequence: !input pause_action
- service: scene.create
  data:
    scene_id: '{{ name_id ~ ''_snapshot'' }}'
    snapshot_entities: !input climate_device
- service: climate.set_hvac_mode
  target:
    entity_id: !input climate_device
  data:
    hvac_mode: 'off'
- choose:
  - conditions: '{{ pause_action is defined and action_first != true }}'
    sequence: !input pause_action
- if:
  - condition: template
    value_template: '{{ timeout != timeout_empty }}'
  then:
    - wait_for_trigger:
      - platform: state
        entity_id: !input doors_windows
        from: 'on'
        to: 'off'
        for: !input resume_delay
      continue_on_timeout: true
      timeout: !input timeout
    - if:
        - condition: template
          value_template: "{{ wait.trigger == none and timeout_action is defined}}"
      then:
        - sequence: !input timeout_action
        - stop: ''
  else:
    - wait_for_trigger:
      - platform: state
        entity_id: !input doors_windows
        from: 'on'
        to: 'off'
        for: !input resume_delay
      continue_on_timeout: false
- condition: not
  conditions:
  - condition: state
    entity_id: !input climate_device
    attribute: fan_mode
    state: 'on'
- condition: state
  entity_id: !input climate_device
  state: 'off'
- service: scene.turn_on
  target:
    entity_id: '{{ ''scene.'' ~ name_id ~ ''_snapshot'' }}'
- choose:
  - conditions:
    - condition: template
      value_template: '{{ ''ecobee'' in device_attr( climate_device ,''manufacturer'') |lower }}'
    - condition: template
      value_template: '{{ states(button_entity) != "unknown" }}'
    sequence:
      - delay:
          seconds: 1
      - service: button.press
        metadata: {}
        data: {}
        target:
          entity_id: '{{ button_entity }}'
- choose:
  - conditions: '{{ resume_action is defined }}'
    sequence: !input resume_action
