blueprint:
  name: HVAC Pause
  description: >-
    Version: 1.8.1

    
    Pauses HVAC when windows/doors open; resumes last state once closed. Includes temperature override protection. [Full documentation](https://github.com/dpredster/HomeAssistantBlueprints/blob/main/hvac_pause.md)


    ### Credits

    * [@raffy-ops](https://github.com/raffy-ops) — [Initial blueprint](https://gist.github.com/raffy-ops/2bdf967036d8d274fb1f62572ed5e545)
  domain: automation
  source_url: https://github.com/dpredster/HomeAssistantBlueprints/blob/main/hvac_pause.yaml
  input:
    climate_device:
      description: Climate entity used for climate control.
      name: Climate Device
      selector:
        entity:
          domain:
          - climate
          multiple: false
    doors_windows:
      description: Group of entities that will activate automation. (Assumes 'on'
        means 'open')
      name: Door and window sensors.
      selector:
        entity:
          domain:
          - group
          - binary_sensor
          multiple: false
    pause_delay:
      description: Time to wait before pausing the HVAC system.
      name: Pause Delay
      default:
        hours: 0
        minutes: 5
        seconds: 0
      selector:
        duration: {}
    resume_delay:
      description: Time to wait before resuming the HVAC system once doors and windows are closed.
      name: Resume Delay
      default:
        hours: 0
        minutes: 0
        seconds: 30
      selector:
        duration: {}
    timeout:
      description: If set, HVAC will ramain off if door/window is not closed prior to timeout value elapsing.
        Set to 0 to disable timeout.
      name: Timeout (optional)
      default:
        hours: 0
        minutes: 0
        seconds: 0
      selector:
        duration: {}
    enable_temp_override:
      description: Enable temperature override feature to resume HVAC if temperature goes outside defined range.
      name: Enable Temperature Override
      default: false
      selector:
        boolean: {}
    temp_sensor:
      description: Temperature sensor to monitor for override conditions.
      name: Temperature Sensor (Optional)
      default: sensor.none
      selector:
        entity:
          domain:
          - sensor
          device_class:
          - temperature
          multiple: false
    temp_min:
      description: Minimum temperature threshold. HVAC resumes if temperature falls below this value. Set to -999 to disable minimum threshold.
      name: Minimum Temperature
      default: -999
      selector:
        number:
          min: -999
          max: 50
          step: 0.5
          unit_of_measurement: "°C"
          mode: box
    temp_max:
      description: Maximum temperature threshold. HVAC resumes if temperature exceeds this value. Set to 999 to disable maximum threshold.
      name: Maximum Temperature
      default: 999
      selector:
        number:
          min: -20
          max: 999
          step: 0.5
          unit_of_measurement: "°C"
          mode: box
    temp_override_duration:
      description: How long temperature must be outside range before resuming HVAC.
      name: Temperature Override Duration
      default:
        hours: 0
        minutes: 5
        seconds: 0
      selector:
        duration: {}
    action_first:
      description: When set to On any defined 'Pause Actions' will occur after the pause delay and prior to
        any other actions.
      name: Action First
      default: false
      selector:
        boolean: {}
    enable_pause_notifications:
      name: Enable Pause Notifications
      description: Send notifications when HVAC is paused
      default: false
      selector:
        boolean:
    enable_resume_notifications:
      name: Enable Resume Notifications
      description: Send notifications when HVAC resumes
      default: false
      selector:
        boolean:
    enable_temp_override_notifications:
      name: Enable Temperature Override Notifications
      description: Send notifications when temperature override activates
      default: false
      selector:
        boolean:
    pause_action:
      description: |
        Optional additional action to perform when climate entity is paused (e.g., send notification).
        For notifications, use the predefined message or write your own custom message text.
        See [documentation](https://github.com/dpredster/HomeAssistantBlueprints/blob/main/hvac_pause.md) for detailed configuration instructions.
        
        Predefined message example: "HVAC paused at 3:45 PM on Dec 12 because Kitchen Window opened"
      name: Pause Action (Optional)
      default: []
      selector:
        action: {}
    resume_action:
      description: |
        Optional additional action to perform when climate entity resumes (e.g., send notification).
        For notifications, use the predefined message or write your own custom message text.
        See [documentation](https://github.com/dpredster/HomeAssistantBlueprints/blob/main/hvac_pause.md) for detailed configuration instructions.
        
        Predefined message example: "HVAC resumed at 3:50 PM on Dec 12 after Kitchen Window closed"
      name: Resume Action (Optional)
      default: []
      selector:
        action: {}
    temp_override_action:
      description: |
        Optional additional action to perform when temperature override activates (e.g., send notification).
        For notifications, use the predefined message or write your own custom message text.
        See [documentation](https://github.com/dpredster/HomeAssistantBlueprints/blob/main/hvac_pause.md) for detailed configuration instructions.
        
        Predefined message example: "Temperature override activated: 18.5°C is below minimum threshold of 20°C"
      name: Temperature Override Action (Optional)
      default: []
      selector:
        action: {}
    timeout_action:
      description: Optional additional action to perform if the timeout value elapses.
      name: Timeout Action (Optional)
      default: []
      selector:
        action: {}
variables:
  action_first: !input action_first
  pause_action: !input pause_action
  resume_action: !input resume_action
  temp_override_action: !input temp_override_action
  timeout_action: !input timeout_action
  enable_pause_notifications: !input enable_pause_notifications
  enable_resume_notifications: !input enable_resume_notifications
  enable_temp_override_notifications: !input enable_temp_override_notifications
  climate_device: !input climate_device
  doors_windows: !input doors_windows
  timeout: !input timeout
  timeout_empty: {'hours':00, 'minutes':00, 'seconds':00}
  name_id: '{{ state_attr( climate_device ,''friendly_name'')|slugify ~ ''_snapshot'' }}'
  button_entity: '{{ ''button.'' ~ name_id ~ ''_clear_hold'' }}'
  enable_temp_override: !input enable_temp_override
  temp_sensor: !input temp_sensor
  temp_min: !input temp_min
  temp_max: !input temp_max
  is_group: '{{ state_attr(doors_windows, "entity_id") is not none }}'
  open_entities_list: |
    {% if state_attr(doors_windows, "entity_id") is not none %}
      {{ expand(state_attr(doors_windows, "entity_id")) | selectattr('state', 'eq', 'on') | map(attribute='name') | list }}
    {% else %}
      {{ [state_attr(doors_windows, 'friendly_name')] if states(doors_windows) == 'on' else [] }}
    {% endif %}
  open_entities: |
    {% if state_attr(doors_windows, "entity_id") is not none %}
      {% set open = expand(state_attr(doors_windows, "entity_id")) | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
      {% if open | count == 1 %}{{ open[0] }}
      {% elif open | count == 2 %}{{ open[0] }} and {{ open[1] }}
      {% elif open | count > 2 %}{{ open[:-1] | join(', ') }}, and {{ open[-1] }}
      {% else %}unknown{% endif %}
    {% else %}
      {{ state_attr(doors_windows, 'friendly_name') if states(doors_windows) == 'on' else 'unknown' }}
    {% endif %}

mode: single
trigger:
- platform: state
  entity_id: !input doors_windows
  from: 'off'
  to: 'on'
  for: !input pause_delay
  id: group_open
- platform: numeric_state
  entity_id: !input temp_sensor
  below: !input temp_min
  for: !input temp_override_duration
  id: temp_too_low
  enabled: '{{ enable_temp_override and temp_sensor not in ["sensor.none", "unavailable", "unknown"] and temp_min > -999 }}'
- platform: numeric_state
  entity_id: !input temp_sensor
  above: !input temp_max
  for: !input temp_override_duration
  id: temp_too_high
  enabled: '{{ enable_temp_override and temp_sensor not in ["sensor.none", "unavailable", "unknown"] and temp_max < 999 }}'
condition: []
action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - temp_too_low
      - temp_too_high
    - condition: template
      value_template: '{{ enable_temp_override == true }}'
    - condition: state
      entity_id: !input climate_device
      state: 'off'
    sequence:
    - service: scene.turn_on
      target:
        entity_id: '{{ ''scene.'' ~ name_id ~ ''_snapshot'' }}'
    - choose:
      - conditions:
        - condition: template
          value_template: '{{ ''ecobee'' in device_attr( climate_device ,''manufacturer'') |lower }}'
        - condition: template
          value_template: '{{ states(button_entity) != "unknown" }}'
        sequence:
          - delay:
              seconds: 1
          - service: button.press
            metadata: {}
            data: {}
            target:
              entity_id: '{{ button_entity }}'
    - if:
      - condition: template
        value_template: "{{ enable_resume_notifications }}"
      then:
        - variables:
            time: "{{ now().strftime('%-I:%M %p on %b %d') }}"
            message: "HVAC resumed at {{ now().strftime('%-I:%M %p on %b %d') }} after windows/doors closed"
        - choose:
          - conditions: '{{ resume_action is defined }}'
            sequence: !input resume_action
      else:
        - choose:
          - conditions: '{{ resume_action is defined }}'
            sequence: !input resume_action
    - if:
      - condition: template
        value_template: "{{ enable_temp_override_notifications }}"
      then:
        - variables:
            time: "{{ now().strftime('%-I:%M %p on %b %d') }}"
            current_temp: "{{ states(temp_sensor) }}"
            threshold: "{{ temp_min if trigger.id == 'temp_too_low' else temp_max }}"
            reason: "{{ 'below minimum threshold' if trigger.id == 'temp_too_low' else 'above maximum threshold' }}"
            message: "Temperature override activated: {{ current_temp }}°C is {{ reason }} of {{ threshold }}°C"
        - choose:
          - conditions: '{{ temp_override_action is defined }}'
            sequence: !input temp_override_action
      else:
        - choose:
          - conditions: '{{ temp_override_action is defined }}'
            sequence: !input temp_override_action
    - stop: 'Temperature override activated - HVAC resumed'
- condition: trigger
  id:
  - group_open
- condition: not
  conditions:
  - condition: state
    entity_id: !input climate_device
    state: 'off'
- choose:
  - conditions: '{{ pause_action is defined and action_first == true }}'
    sequence: !input pause_action
- service: scene.create
  data:
    scene_id: '{{ name_id ~ ''_snapshot'' }}'
    snapshot_entities: !input climate_device
- service: climate.set_hvac_mode
  target:
    entity_id: !input climate_device
  data:
    hvac_mode: 'off'
- if:
  - condition: template
    value_template: "{{ enable_pause_notifications }}"
  then:
    - variables:
        time: "{{ now().strftime('%-I:%M %p on %b %d') }}"
        opened_items: |
          {% if state_attr(doors_windows, "entity_id") is not none %}
            {% set open = expand(state_attr(doors_windows, "entity_id")) | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}
            {% if open | count == 1 %}{{ open[0] }}
            {% elif open | count == 2 %}{{ open[0] }} and {{ open[1] }}
            {% elif open | count > 2 %}{{ open[:-1] | join(', ') }}, and {{ open[-1] }}
            {% else %}windows/doors{% endif %}
          {% else %}
            {{ state_attr(doors_windows, 'friendly_name') if states(doors_windows) == 'on' else 'windows/doors' }}
          {% endif %}
        message: "HVAC paused at {{ now().strftime('%-I:%M %p on %b %d') }} because {{ opened_items }} opened"
    - choose:
      - conditions: '{{ pause_action is defined and action_first != true }}'
        sequence: !input pause_action
  else:
    - choose:
      - conditions: '{{ pause_action is defined and action_first != true }}'
        sequence: !input pause_action
- if:
  - condition: template
    value_template: '{{ timeout != timeout_empty }}'
  then:
    - wait_for_trigger:
      - platform: state
        entity_id: !input doors_windows
        from: 'on'
        to: 'off'
        for: !input resume_delay
      continue_on_timeout: true
      timeout: !input timeout
    - if:
        - condition: template
          value_template: "{{ wait.trigger == none and timeout_action is defined}}"
      then:
        - sequence: !input timeout_action
        - stop: ''
  else:
    - wait_for_trigger:
      - platform: state
        entity_id: !input doors_windows
        from: 'on'
        to: 'off'
        for: !input resume_delay
      continue_on_timeout: false
- condition: not
  conditions:
  - condition: state
    entity_id: !input climate_device
    attribute: fan_mode
    state: 'on'
- condition: state
  entity_id: !input climate_device
  state: 'off'
- variables:
    last_closed_sensor: |
      {% if state_attr(doors_windows, "entity_id") is not none %}
        {% set all_entities = state_attr(doors_windows, "entity_id") %}
        {% set closed_entities = expand(all_entities) | selectattr('state', 'eq', 'off') | sort(attribute='last_changed', reverse=true) | list %}
        {% if closed_entities | count > 0 %}{{ closed_entities[0].name }}
        {% else %}unknown{% endif %}
      {% else %}
        {{ state_attr(doors_windows, 'friendly_name') if states(doors_windows) == 'off' else 'unknown' }}
      {% endif %}
- service: scene.turn_on
  target:
    entity_id: '{{ ''scene.'' ~ name_id ~ ''_snapshot'' }}'
- choose:
  - conditions:
    - condition: template
      value_template: '{{ ''ecobee'' in device_attr( climate_device ,''manufacturer'') |lower }}'
    - condition: template
      value_template: '{{ states(button_entity) != "unknown" }}'
    sequence:
      - delay:
          seconds: 1
      - service: button.press
        metadata: {}
        data: {}
        target:
          entity_id: '{{ button_entity }}'
- if:
  - condition: template
    value_template: "{{ enable_resume_notifications }}"
  then:
    - variables:
        time: "{{ now().strftime('%-I:%M %p on %b %d') }}"
        closed_sensor: "{{ last_closed_sensor }}"
        message: "HVAC resumed at {{ now().strftime('%-I:%M %p on %b %d') }} after {{ last_closed_sensor }} closed"
    - choose:
      - conditions: '{{ resume_action is defined }}'
        sequence: !input resume_action
  else:
    - choose:
      - conditions: '{{ resume_action is defined }}'
        sequence: !input resume_action
